export const questions = [
  {
    subject: "science",
    questions: [
      {
        id: 1,
        question: "What is the chemical symbol for water?",
        options: ["O2", "H2O", "CO2", "HO2"],
        answer: "H2O",
      },
      {
        id: 2,
        question: "Which planet is known as the Red Planet?",
        options: ["Venus", "Mars", "Jupiter", "Mercury"],
        answer: "Mars",
      },
      {
        id: 3,
        question: "What gas do humans exhale?",
        options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
        answer: "Carbon Dioxide",
      },
      {
        id: 4,
        question: "What is the center of an atom called?",
        options: ["Electron", "Nucleus", "Proton", "Neutron"],
        answer: "Nucleus",
      },
      {
        id: 5,
        question: "Which force keeps us on the ground?",
        options: ["Magnetism", "Friction", "Gravity", "Electricity"],
        answer: "Gravity",
      },
      {
        id: 6,
        question: "What part of the cell contains genetic material?",
        options: ["Mitochondria", "Nucleus", "Ribosome", "Cytoplasm"],
        answer: "Nucleus",
      },
      {
        id: 7,
        question: "What is the boiling point of water at sea level?",
        options: ["50°C", "100°C", "150°C", "200°C"],
        answer: "100°C",
      },
      {
        id: 8,
        question: "Which organ pumps blood through the body?",
        options: ["Lungs", "Brain", "Heart", "Kidneys"],
        answer: "Heart",
      },
      {
        id: 9,
        question: "What type of energy is stored in food?",
        options: [
          "Kinetic Energy",
          "Chemical Energy",
          "Thermal Energy",
          "Nuclear Energy",
        ],
        answer: "Chemical Energy",
      },
      {
        id: 10,
        question: "Which part of the plant makes food?",
        options: ["Roots", "Stem", "Leaves", "Flowers"],
        answer: "Leaves",
      },
    ],
  },
  {
    subject: "math",
    questions: [
      {
        id: 1,
        question: "What is 12 × 8?",
        options: ["96", "86", "88", "108"],
        answer: "96",
      },
      {
        id: 2,
        question: "What is the square root of 144?",
        options: ["10", "11", "12", "13"],
        answer: "12",
      },
      {
        id: 3,
        question: "What is 25% of 200?",
        options: ["25", "50", "75", "100"],
        answer: "50",
      },
      {
        id: 4,
        question: "What is the value of π (pi) approximately?",
        options: ["2.14", "3.14", "4.14", "3.41"],
        answer: "3.14",
      },
      {
        id: 5,
        question: "What is 15²?",
        options: ["200", "210", "225", "250"],
        answer: "225",
      },
      {
        id: 6,
        question: "What is 1000 ÷ 25?",
        options: ["25", "30", "35", "40"],
        answer: "40",
      },
      {
        id: 7,
        question: "Solve: 9 + (6 × 2)",
        options: ["21", "30", "15", "19"],
        answer: "21",
      },
      {
        id: 8,
        question: "What is the perimeter of a square with side 5cm?",
        options: ["10cm", "15cm", "20cm", "25cm"],
        answer: "20cm",
      },
      {
        id: 9,
        question: "What is the next prime number after 7?",
        options: ["9", "10", "11", "13"],
        answer: "11",
      },
      {
        id: 10,
        question: "What is 3/4 of 100?",
        options: ["25", "50", "75", "100"],
        answer: "75",
      },
    ],
  },
  {
    subject: "history",
    questions: [
      {
        id: 1,
        question: "Who was the first President of the United States?",
        options: ["George Washington", "Abraham Lincoln", "John Adams", "Thomas Jefferson"],
        answer: "George Washington",
      },
      {
        id: 2,
        question: "In which year did World War II end?",
        options: ["1942", "1945", "1948", "1950"],
        answer: "1945",
      },
      {
        id: 3,
        question: "Who discovered America in 1492?",
        options: ["Christopher Columbus", "Marco Polo", "Vasco da Gama", "Ferdinand Magellan"],
        answer: "Christopher Columbus",
      },
      {
        id: 4,
        question: "Which empire built the Colosseum?",
        options: ["Greek", "Roman", "Persian", "Egyptian"],
        answer: "Roman",
      },
      {
        id: 5,
        question: "Who was the first man to step on the moon?",
        options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"],
        answer: "Neil Armstrong",
      },
      {
        id: 6,
        question: "Which civilization built the pyramids?",
        options: ["Greek", "Roman", "Egyptian", "Mayan"],
        answer: "Egyptian",
      },
      {
        id: 7,
        question: "Who was known as the 'Maid of Orléans'?",
        options: ["Joan of Arc", "Cleopatra", "Queen Victoria", "Marie Curie"],
        answer: "Joan of Arc",
      },
      {
        id: 8,
        question: "What year did the Berlin Wall fall?",
        options: ["1987", "1989", "1990", "1991"],
        answer: "1989",
      },
      {
        id: 9,
        question: "Who was the leader of the Soviet Union during World War II?",
        options: ["Joseph Stalin", "Vladimir Lenin", "Mikhail Gorbachev", "Nikita Khrushchev"],
        answer: "Joseph Stalin",
      },
      {
        id: 10,
        question: "Which ancient civilization invented democracy?",
        options: ["Roman", "Greek", "Egyptian", "Chinese"],
        answer: "Greek",
      },
    ],
  },
  {
    subject: "geography",
    questions: [
      {
        id: 1,
        question: "What is the largest continent on Earth?",
        options: ["Africa", "Asia", "North America", "Europe"],
        answer: "Asia",
      },
      {
        id: 2,
        question: "Which is the longest river in the world?",
        options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
        answer: "Nile",
      },
      {
        id: 3,
        question: "Which country has the largest population?",
        options: ["India", "China", "USA", "Russia"],
        answer: "China",
      },
      {
        id: 4,
        question: "Which desert is the largest in the world?",
        options: ["Sahara", "Gobi", "Kalahari", "Antarctic"],
        answer: "Antarctic",
      },
      {
        id: 5,
        question: "Which is the tallest mountain in the world?",
        options: ["K2", "Mount Everest", "Kilimanjaro", "Denali"],
        answer: "Mount Everest",
      },
      {
        id: 6,
        question: "Which ocean is the largest?",
        options: ["Atlantic", "Indian", "Pacific", "Arctic"],
        answer: "Pacific",
      },
      {
        id: 7,
        question: "Which country is known as the Land of the Rising Sun?",
        options: ["Japan", "China", "Thailand", "Korea"],
        answer: "Japan",
      },
      {
        id: 8,
        question: "Which is the smallest country in the world?",
        options: ["Vatican City", "Monaco", "Malta", "Luxembourg"],
        answer: "Vatican City",
      },
      {
        id: 9,
        question: "Which river flows through Egypt?",
        options: ["Nile", "Amazon", "Danube", "Mississippi"],
        answer: "Nile",
      },
      {
        id: 10,
        question: "Which continent is the Sahara Desert located in?",
        options: ["Asia", "Africa", "Australia", "South America"],
        answer: "Africa",
      },
    ],
  },
  {
    subject: "art",
    questions: [
      {
        id: 1,
        question: "Who painted the Mona Lisa?",
        options: ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
        answer: "Leonardo da Vinci",
      },
      {
        id: 2,
        question: "The Starry Night is a famous painting by which artist?",
        options: ["Claude Monet", "Vincent van Gogh", "Salvador Dalí", "Rembrandt"],
        answer: "Vincent van Gogh",
      },
      {
        id: 3,
        question: "Which art style is Pablo Picasso known for?",
        options: ["Cubism", "Impressionism", "Realism", "Surrealism"],
        answer: "Cubism",
      },
      {
        id: 4,
        question: "The Sistine Chapel ceiling was painted by?",
        options: ["Raphael", "Michelangelo", "Donatello", "Caravaggio"],
        answer: "Michelangelo",
      },
      {
        id: 5,
        question: "Which artist is known for melting clocks in paintings?",
        options: ["Salvador Dalí", "Claude Monet", "Paul Cézanne", "Frida Kahlo"],
        answer: "Salvador Dalí",
      },
      {
        id: 6,
        question: "What nationality was Claude Monet?",
        options: ["Spanish", "Italian", "French", "Dutch"],
        answer: "French",
      },
      {
        id: 7,
        question: "Which artist cut off part of his ear?",
        options: ["Pablo Picasso", "Vincent van Gogh", "Henri Matisse", "Paul Gauguin"],
        answer: "Vincent van Gogh",
      },
      {
        id: 8,
        question: "Which famous sculpture is by Auguste Rodin?",
        options: ["The Thinker", "David", "Venus de Milo", "The Kiss"],
        answer: "The Thinker",
      },
      {
        id: 9,
        question: "Which art movement is Claude Monet associated with?",
        options: ["Cubism", "Impressionism", "Surrealism", "Realism"],
        answer: "Impressionism",
      },
      {
        id: 10,
        question: "The Last Supper is a famous painting by?",
        options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Rembrandt"],
        answer: "Leonardo da Vinci",
      },
    ],
  },
  {
    subject: "computer-science",
    questions: [
      {
        id: 1,
        question: "What does CPU stand for?",
        options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Control Processing Unit"],
        answer: "Central Processing Unit",
      },
      {
        id: 2,
        question: "Which programming language is known as the 'mother of all languages'?",
        options: ["C", "Java", "Python", "Assembly"],
        answer: "C",
      },
      {
        id: 3,
        question: "What does HTML stand for?",
        options: ["HyperText Markup Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language", "Hyper Tool Multi Language"],
        answer: "HyperText Markup Language",
      },
      {
        id: 4,
        question: "What does RAM stand for?",
        options: ["Random Access Memory", "Read Access Memory", "Run All Memory", "Rapid Access Memory"],
        answer: "Random Access Memory",
      },
      {
        id: 5,
        question: "Which company developed the Windows operating system?",
        options: ["Apple", "Microsoft", "IBM", "Google"],
        answer: "Microsoft",
      },
      {
        id: 6,
        question: "What is the main language used for Android app development?",
        options: ["Swift", "Kotlin", "Java", "C#"],
        answer: "Java",
      },
      {
        id: 7,
        question: "What is the binary representation of the number 5?",
        options: ["101", "110", "111", "100"],
        answer: "101",
      },
      {
        id: 8,
        question: "Which of these is a NoSQL database?",
        options: ["MySQL", "MongoDB", "PostgreSQL", "Oracle"],
        answer: "MongoDB",
      },
      {
        id: 9,
        question: "Who is known as the father of computers?",
        options: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"],
        answer: "Charles Babbage",
      },
      {
        id: 10,
        question: "What does 'AI' stand for?",
        options: ["Automated Interface", "Artificial Intelligence", "Applied Innovation", "Algorithmic Integration"],
        answer: "Artificial Intelligence",
      },
    ],
  },
];
